#每周1，4，6自动更新refresh_token1 1235
name: Update Token

on: 
  release:
    types: [published]  # 当发布新版本时触发
  push:
    tags:
    - 'v*'  # 当推送带有特定标签的提交时触发
  #  branches: 
  #    - master # 当推送到master分支时触发（当前被注释掉）
  schedule:
    - cron: '10 10 * * 1,4,6'   # 设置定时任务，每周一、四、六的10:10执行
  watch:
    types: [started]   # 当有人star这个仓库时触发
   
jobs:
  build:
    runs-on: ubuntu-latest  # 运行在最新版本的Ubuntu虚拟环境上
    if: github.event.repository.owner.id == github.event.sender.id  # 自己点的 start
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Install requests and nacl #安装requests和nacl模块
      run: |
        pip install requests
        pip install PyNaCl
    - name: update secrets #更新token到secret
      env: 
        #github的账号信息
        GH_TOKEN: ${{ secrets.GH_TOKEN }} 
        GH_REPO: ${{ github.repository }}
        #以下是微软的账号信息（修改以下，类推复制增加）
        APP_NUM: ${{ secrets.APP_NUM }} 
        #账号/应用1
        MS_TOKEN_1: ${{ secrets.MS_TOKEN }} 
        CLIENT_ID_1: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET_1: ${{ secrets.CLIENT_SECRET }}
        #账号/应用2
        MS_TOKEN_2: ${{ secrets.MS_TOKEN_2 }} 
        CLIENT_ID_2: ${{ secrets.CLIENT_ID_2 }}
        CLIENT_SECRET_2: ${{ secrets.CLIENT_SECRET_2 }}
        #账号/应用3
        MS_TOKEN_3: ${{ secrets.MS_TOKEN_3 }} 
        CLIENT_ID_3: ${{ secrets.CLIENT_ID_3 }}
        CLIENT_SECRET_3: ${{ secrets.CLIENT_SECRET_3 }}
        #账号/应用4
        MS_TOKEN_4: ${{ secrets.MS_TOKEN_4 }} 
        CLIENT_ID_4: ${{ secrets.CLIENT_ID_4 }}
        CLIENT_SECRET_4: ${{ secrets.CLIENT_SECRET_4 }}
        #账号/应用5
        MS_TOKEN_5: ${{ secrets.MS_TOKEN_5 }} 
        CLIENT_ID_5: ${{ secrets.CLIENT_ID_5 }}
        CLIENT_SECRET_5: ${{ secrets.CLIENT_SECRET_5 }}
        #如此类推，自己复制增加账号/应用
        MS_TOKEN_n: ${{ secrets.MS_TOKEN_n }} 
        CLIENT_ID_n: ${{ secrets.CLIENT_ID_n }}
        CLIENT_SECRET_n: ${{ secrets.CLIENT_SECRET_n }}
      run: |
        python UpdateToken.py  # 执行更新Token的Python脚本
